### ISSUE TITLE
关于nohup报错的问题

### ISSUE THREAD

**Issue by wangze09** [CyberCatQ/pyCADD#11]
您好！
       感谢您精彩的代码，我目前运行的时候出现了一个小问题，烦请您抽空查看一下。就是我直接在服务器运行动力学模拟相关的Python文件时是没有问题的，但是我一旦nohup python之后就会出现如下报错：RuntimeError: Amber or AmberTools is not installed or not in PATH. 由于后续超算上面不能直接在登录节点直接运行相关python命令，还是需要进行nohup后台挂起；请问这个问题应该如何解决呢？

**Comment by CyberCatQ** [comment]
您好，首先感谢您对pyCADD的使用。
pyCADD设计之初仅用于本地服务器计算，尚未在超算/云服务器上进行过测试，给您带来不便感到抱歉。

您提到的错误RuntimeError: Amber or AmberTools is not installed or not in PATH.是因为当前的shell环境中，pyCADD未能找到Amber/AmberTools相关二进制可执行文件，这通常可能是因为运行Amber任务前未执行过`source $AMBERHOME/amber.sh`导致的（AMBERHOME为您的amber安装目录）。

根据我的经验，您可以编写一个shell脚本文件（如`submit.sh`），在其中首先写入 `source $AMBERHOME/amber.sh` 后再调用您的python指令，如`python script.py`，并使用slurm等作业调度系统提交任务，或尝试使用`nohup bash submit.sh`等其他方式开始运行任务。关于超算/云服务器任务提交的必要步骤，请进一步咨询您的超算服务器管理员。

**Comment by wangze09** [comment]
好的，我了解啦，非常感谢您的耐心解答！
